dataset:
  name: imagenet10
  num_classes: 10
  pre_size: 256
  image_size: 224

  interpolation: bicubic # following clip.
  normalization_type: clip ## imagenet | clip.

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/imagenet/train_imagenet.txt
    batch_size: 128
    few_shot: 16
    randseed: 0
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/imagenet/val_imagenet.txt
    batch_size: 256
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/imagenet10/test_imagenet10_id.txt
    batch_size: 25
    shuffle: False

ood_dataset:
  name: imagenet20
  num_classes: 20

  dataset_class: ImglistDataset
  interpolation: bicubic
  normalization_type: clip
  batch_size: 25
  shuffle: False # for Test time method, shuffle is performed in the trainer, please verify.

  pre_size: 256
  image_size: 224
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  split_names: [val, nearood]
  val:
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/imagenet10/test_imagenet10_id.txt
  nearood:
    datasets: [imagenet20]
    imagenet20:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/imagenet20/test_imagenet20_ood.txt


