name: openood
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - attr=2.5.1=h166bdaf_1
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.4.26=py39h06a4308_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h74842e3_2
  - cudatoolkit=10.1.243=h6d9799a_13
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dbus=1.16.2=h3c4dab8_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.0=py39h9399b63_0
  - freetype=2.13.3=ha770c72_1
  - gettext=0.24.1=h5888daf_0
  - gettext-tools=0.24.1=h5888daf_0
  - glib=2.84.2=h6287aef_0
  - glib-tools=2.84.2=h4833e2c_0
  - graphite2=1.3.13=h59595ed_1003
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - harfbuzz=11.2.1=h3beb420_0
  - icu=75.1=he02047a_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - json5=0.9.6=pyhd3eb1b0_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libasprintf=0.24.1=h8e693c7_0
  - libasprintf-devel=0.24.1=h8e693c7_0
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=20_linux64_openblas
  - libclang-cpp20.1=20.1.5=default_h1df26ce_1
  - libclang13=20.1.5=default_he06ed0a_1
  - libcups=2.3.3=h4637d8d_4
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.24.1=h5888daf_0
  - libgettextpo-devel=0.24.1=h5888daf_0
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran-ng=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h3618099_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_2
  - libgpg-error=1.55=h3f2d84a_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=20_linux64_openblas
  - libllvm20=20.1.5=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_1
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.5=h27ae623_0
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.49.2=hee588c1_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libsystemd0=257.4=h4e0b6ca_1
  - libtiff=4.7.0=hf01ce69_5
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.10.0=h65c71a3_0
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - matplotlib=3.7.3=py39hf3d152e_0
  - matplotlib-base=3.7.3=py39he9076e7_0
  - mpg123=1.32.9=hc50e24c_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h2d0b736_3
  - nspr=4.36=h5888daf_0
  - nss=3.111=h159eef7_0
  - numpy=1.26.4=py39h474f0d3_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.0=h7b32b05_1
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.45=hc749103_0
  - pillow=11.2.1=py39h15c0740_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.0=h29eaf8c_0
  - ply=3.11=pyhd8ed1ab_3
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulseaudio-client=17.0=hac146a9_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=5.15.11=py39h08c78a2_0
  - pyqt5-sip=12.17.0=py39hf88036b_0
  - python=3.9.22=h85ef794_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.9=7_cp39
  - qt-main=5.15.15=hea1682b_4
  - readline=8.2=h8c095d6_2
  - scikit-learn=0.24.2=py39h7c5d8c9_1
  - setuptools=80.8.0=pyhff2d567_0
  - sip=6.10.0=py39hf88036b_0
  - six=1.17.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.5.1=py39h8cd3c5a_0
  - tqdm=4.62.3=pyhd8ed1ab_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.44=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.0
      - aiosignal==1.3.2
      - airportsdata==20250523
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astor==0.8.1
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==14.4.0
      - blake3==1.0.5
      - cachetools==6.0.0
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==4.0.2
      - compressed-tensors==0.9.3
      - cupy-cuda12x==13.4.1
      - cython==3.1.1
      - decorator==5.2.1
      - deprecated==1.2.18
      - depyf==0.18.0
      - diffdist==0.1
      - dill==0.4.0
      - diskcache==5.6.3
      - dnspython==2.7.0
      - einops==0.8.1
      - email-validator==2.2.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - faiss-gpu==1.7.2
      - fastapi==0.115.12
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - filelock==3.18.0
      - frozenlist==1.6.0
      - fsspec==2025.5.1
      - ftfy==6.3.1
      - gguf==0.16.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - h11==0.16.0
      - hf-xet==1.1.2
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.32.0
      - idna==3.10
      - imageio==2.37.0
      - imgaug==0.4.0
      - importlib-metadata==8.0.0
      - interegular==0.3.3
      - ipdb==0.13.13
      - ipython==8.18.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - lark==1.2.2
      - lazy-loader==0.4
      - libmr==0.1.9
      - llguidance==0.7.24
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistral-common==1.5.6
      - mpmath==1.3.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.4.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - numba==0.60.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.82.0
      - openai-clip==1.0.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.9
      - outlines==0.0.34
      - outlines-core==0.1.26
      - pandas==2.2.3
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post5
      - pexpect==4.9.0
      - prometheus-client==0.22.0
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - protobuf==4.25.7
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pycountry==24.6.1
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - qwen-vl-utils==0.0.11
      - ray==2.46.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - rich-toolkit==0.14.6
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - shapely==2.0.7
      - shellingham==1.5.4
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.46.2
      - sympy==1.13.1
      - tifffile==2024.8.30
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.6.0+cu124
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - traitlets==5.14.3
      - transformers==4.52.3
      - triton==3.2.0
      - typer==0.15.4
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.4.0
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - vllm==0.4.3
      - vllm-flash-attn==2.5.8.post2
      - watchfiles==1.0.5
      - wcwidth==0.2.13
      - websockets==15.0.1
      - wrapt==1.17.2
      - xformers==0.0.26.post1
      - xgrammar==0.1.18
      - yarl==1.20.0
prefix: /data1/wenjie/projects/miniconda3/envs/openood
