dataset:
  name: pet
  num_classes: 18
  pre_size: 224
  image_size: 224

  interpolation: bilinear
  normalization_type: clip

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar10/train_cifar10.txt
    batch_size: 200
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar10/val_cifar10.txt
    batch_size: 200
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/pet/test_pet_id.txt
    batch_size: 1
    shuffle: False

ood_dataset:
  name: pet_ood
  num_classes: 18
  pre_size: 224
  image_size: 224

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset
  batch_size: 1
  shuffle: False

  split_names: [val, nearood, farood]
  val:
    data_dir: ./data/images_largescale/
    imglist_pth: ./data/benchmark_imglist/pet/test_pet_ood.txt
  nearood:
    datasets: [ninco]
    ninco:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/imagenet/test_ninco_less.txt
  farood:
    datasets: [pet_ood]
    pet_ood:
      data_dir: ./data/images_largescale/
      imglist_pth: ./data/benchmark_imglist/pet/test_pet_ood.txt

